[build]
  # ESTE COMANDO INSTALA FLUTTER 3.38.1 Y LUEGO COMPILA EL SITIO
  command = "git clone https://github.com/flutter/flutter.git -b 3.38.1 --depth 1 && export PATH=\"$PATH:$(pwd)/flutter/bin\" && flutter doctor && flutter pub get && flutter build web --release"

  # Directorio donde se encuentra el resultado de la compilacion
  publish = "build/web"